//
//  UserCellPresenter.swift
//  CleanGitUsersList
//
//  Created by Михаил Звягинцев on 23.10.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UserCellPresentationLogic {

    func presentUserImage(response: UserCell.ShowUserCell.Response)
    func presentDefaultImage()
}

class UserCellPresenter: UserCellPresentationLogic {
    func presentDefaultImage() {
        viewController?.displayDefaultImage()
    }
    
    weak var viewController: UserCellDisplayLogic?

    func presentUserImage(response: UserCell.ShowUserCell.Response) {
        let viewModel = UserCell.ShowUserCell.ViewModel(imageData: response.imageData)
        viewController?.displayUserImage(viewModel: viewModel)
    }
}
