//
//  UserDetailsWorker.swift
//  CleanGitUsersList
//
//  Created by Михаил Звягинцев on 23.10.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class UserDetailsWorker {

    func fetchUserData(from url: URL, complition: @escaping(Result<UserInfoModel?, Error>) -> Void) {
        NetworkManager.shared.fetchData(from: url, resultType: UserInfoModel.self) { result in
            do {
                let userInfo = try result.get()
                complition(.success(userInfo))
            } catch {
                complition(.failure(error))
            }
        }
    }
}
