//
//  UserDetailsPresenter.swift
//  CleanGitUsersList
//
//  Created by Михаил Звягинцев on 23.10.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UserDetailsPresentationLogic {
    func presentDetails(response: UserDetails.ShowDetails.Response)
    func presentError(error: Error)
}

class UserDetailsPresenter: UserDetailsPresentationLogic {

    weak var viewController: UserDetailsDisplayLogic?
    
    func presentDetails(response: UserDetails.ShowDetails.Response) {
        var userInfo: [String] = []
        if let name = response.userDetails?.name {userInfo.append("Name: \(name.capitalized)")}
        if let location = response.userDetails?.location {userInfo.append("Location: \(location.capitalized)")}
        if let company = response.userDetails?.company {userInfo.append("Company: \"\(company.capitalized)\"")}
        if let followers = response.userDetails?.followers {userInfo.append("Number of followers: \(followers)")}
        if let gits = response.userDetails?.publicGists {userInfo.append("Number of public git's: \(gits)")}
        if let repos = response.userDetails?.publicRepos {userInfo.append("Number of public repositories: \(repos)")}
        let userName = response.userDetails?.login?.capitalized ?? ""
        let viewModel = UserDetails.ShowDetails.ViewModel(userName: userName, userInfo: userInfo, userImageData: response.userImageData)
        viewController?.displayUserDetails(viewModel: viewModel)
    }
    
    func presentError(error: Error) {
        viewController?.displayAlert(with: error.localizedDescription)
    }
}
