//
//  UserDetailsInteractor.swift
//  CleanGitUsersList
//
//  Created by Михаил Звягинцев on 23.10.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UserDetailsBusinessLogic {

    func showDetails(request: UserDetails.ShowDetails.Request)
}

protocol UserDetailsDataStore {

    var userDetails: UserDetails? {get}
}

class UserDetailsInteractor: UserDetailsBusinessLogic, UserDetailsDataStore {

    var presenter: UserDetailsPresentationLogic?
    var worker: UserDetailsWorker?
    var userDetails: UserDetails?

    func showDetails(request: UserDetails.ShowDetails.Request) {
        worker = UserDetailsWorker()
        if let userUrl = URL(string: request.userUrl) {
            worker?.fetchUserData(from: userUrl, complition: { result in
                do {
                    let userInfo = try result.get()
                    if let url = URL(string: request.userImageUrl) {
                        ImageDataLoader.shared.loadImage(url: url) {result in
                            do {
                                let imageData = try result.get()
                                self.presenter?.presentDetails(response: UserDetails.ShowDetails.Response(userDetails: userInfo, userImageData: imageData))
                            } catch {
                                self.presenter?.presentDetails(response: UserDetails.ShowDetails.Response(userDetails: userInfo, userImageData: Data()))
                            }
                        }
                    }
                } catch {
                    self.presenter?.presentError(error: error)
                }
            })
        }
    }

}
