//
//  UsersListInteractor.swift
//  CleanGitUsersList
//
//  Created by Михаил Звягинцев on 22.10.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UsersListBusinessLogic {

    func showUsersList()
}

protocol UsersListDataStore
{
    var usersURLs: [String] {get set}
    var usersImagesURLs: [String] {get set}
}

class UsersListInteractor: UsersListBusinessLogic, UsersListDataStore {

    var presenter: UsersListPresentationLogic?
    var worker: UsersListWorker?
    var usersList: UsersList?
    var usersURLs: [String] = []
    var usersImagesURLs: [String] = []

    func showUsersList() {
        worker = UsersListWorker()
        worker?.fetchUsersData(complition: { result in
            do {
                let usersInfo = try result.get()
                self.presenter?.presentUsersList(response: UsersList.ShowUsersList.Response(users: usersInfo ?? []))
                let response = UsersList.ShowUsersList.Response(users: usersInfo ?? [])
                self.presenter?.presentUsersList(response: response)
                self.usersURLs = []
                usersInfo?.forEach{
                    self.usersURLs.append($0.url ?? "")
                    self.usersImagesURLs.append($0.avatarUrl ?? "")
                }
            }  catch {
                self.presenter?.presentError(error: error)
            }
        })
    }
}
