//
//  UsersListRouter.swift
//  CleanGitUsersList
//
//  Created by Михаил Звягинцев on 22.10.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UsersListRouterInput {

    func showUserDetailViewController(at: Int)
}

protocol UsersListDataPassing {
    
  var dataStore: UsersListDataStore? { get }
}

class UsersListRouter: UsersListRouterInput {

    weak var viewController: UsersListViewController?
    var dataStore: UsersListDataStore?

    func showUserDetailViewController(at index: Int) {
        let userDetailViewController = UserDetailsViewController()
        guard let vc = viewController, let urls = dataStore?.usersURLs else {
            return
        }
        vc.navigationController?.pushViewController(userDetailViewController, animated: true)
        userDetailViewController.userUrl = urls[index]
        userDetailViewController.userImageUrl = dataStore?.usersImagesURLs[index] ?? ""
    }
}
