//
//  UsersListWorker.swift
//  CleanGitUsersList
//
//  Created by Михаил Звягинцев on 22.10.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

class UsersListWorker {
    
    func fetchUsersData(complition: @escaping(Result<[UserListDataModel]?, Error>) -> Void) {
        guard let url = URL(string: "https://api.github.com/users") else {
            complition(.failure(CustomErrors.serverEnable))
            return
        }
        NetworkManager.shared.fetchData(from: url, resultType: [UserListDataModel].self) { result in
            do {
                let userInfo = try result.get()
                complition(.success(userInfo))
            } catch {
                complition(.failure(error))
            }
        }
    }
}
